import type { AccessRequest, MockUser, SipAccount } from "./types";

const DAY = 86_400_000;
const iso = (offsetDays: number) =>
  new Date(Date.now() + offsetDays * DAY).toISOString();

export const MOCK_USERS: MockUser[] = [
  {
    id: "u-admin",
    identifier: "n.varga@flexisip.ops",
    password: "command",
    name: "Nora Varga",
    org: "Network Operations",
    role: "admin",
    modules: ["sip", "esim"],
    blurb: "Full platform access, approvals, delete rights",
  },
  {
    id: "u-res-sip",
    identifier: "d.moreau@lineabridge.fr",
    password: "command",
    name: "Damien Moreau",
    org: "LineaBridge SARL",
    role: "reseller",
    modules: ["sip"],
    blurb: "Reseller — SIP module approved, eSIM locked",
  },
  {
    id: "u-res-esim",
    identifier: "a.okonkwo@zentracom.ng",
    password: "command",
    name: "Adaeze Okonkwo",
    org: "ZentraCom Nigeria",
    role: "reseller",
    modules: ["esim"],
    blurb: "Reseller — eSIM only, SIP panel locked",
  },
  {
    id: "u-res-both",
    identifier: "m.deleon@arcvoice.ph",
    password: "command",
    name: "Mateo de León",
    org: "ArcVoice Telecom",
    role: "reseller",
    modules: ["sip", "esim"],
    blurb: "Reseller — both modules approved",
  },
  {
    id: "u-end",
    identifier: "1042@sip.flexivoice.net",
    password: "command",
    name: "Priya Raghunathan",
    role: "enduser",
    modules: [],
    accountId: "acc-1042",
    blurb: "End-user — signs in with SIP credentials",
  },
];

export const MOCK_ACCOUNTS: SipAccount[] = [
  {
    id: "acc-1042",
    sipId: "1042@sip.flexivoice.net",
    displayName: "Priya Raghunathan",
    email: "priya.r@northgate-clinic.in",
    disabled: false,
    expiresAt: iso(9),
    createdAt: iso(-201),
    createdById: "u-admin",
    createdByName: "Nora Varga",
    notes: "Reception line, Northgate Clinic",
  },
  {
    id: "acc-2210",
    sipId: "2210@sip.flexivoice.net",
    displayName: "Helsinki Dispatch Desk",
    email: "dispatch@nordlogistik.fi",
    disabled: false,
    expiresAt: iso(184),
    createdAt: iso(-98),
    createdById: "u-admin",
    createdByName: "Nora Varga",
  },
  {
    id: "acc-3015",
    sipId: "3015@sip.flexivoice.net",
    displayName: "Ines Fabre",
    email: "ines.fabre@lineabridge.fr",
    disabled: false,
    expiresAt: iso(41),
    createdAt: iso(-76),
    createdById: "u-res-sip",
    createdByName: "Damien Moreau",
  },
  {
    id: "acc-3016",
    sipId: "3016@sip.flexivoice.net",
    displayName: "Atelier Vaugirard — Front",
    email: "contact@vaugirard-atelier.fr",
    disabled: false,
    expiresAt: iso(4),
    createdAt: iso(-361),
    createdById: "u-res-sip",
    createdByName: "Damien Moreau",
    notes: "Renewal reminder already sent twice",
  },
  {
    id: "acc-3021",
    sipId: "3021@sip.flexivoice.net",
    displayName: "Bastien Roux",
    email: "b.roux@lineabridge.fr",
    disabled: true,
    expiresAt: iso(120),
    createdAt: iso(-140),
    createdById: "u-res-sip",
    createdByName: "Damien Moreau",
    notes: "Suspended pending billing review",
  },
  {
    id: "acc-3033",
    sipId: "3033@sip.flexivoice.net",
    displayName: "Marseille Warehouse Gate",
    email: "gate@lineabridge.fr",
    disabled: false,
    expiresAt: iso(-12),
    createdAt: iso(-378),
    createdById: "u-res-sip",
    createdByName: "Damien Moreau",
  },
  {
    id: "acc-4101",
    sipId: "4101@sip.flexivoice.net",
    displayName: "Mateo de León",
    email: "m.deleon@arcvoice.ph",
    disabled: false,
    expiresAt: iso(233),
    createdAt: iso(-233),
    createdById: "u-res-both",
    createdByName: "Mateo de León",
  },
  {
    id: "acc-4108",
    sipId: "4108@sip.flexivoice.net",
    displayName: "Cebu Support Queue",
    email: "support@arcvoice.ph",
    disabled: false,
    expiresAt: iso(18),
    createdAt: iso(-52),
    createdById: "u-res-both",
    createdByName: "Mateo de León",
  },
  {
    id: "acc-4112",
    sipId: "4112@sip.flexivoice.net",
    displayName: "Reyna Castillo",
    email: "r.castillo@arcvoice.ph",
    disabled: true,
    expiresAt: iso(-45),
    createdAt: iso(-410),
    createdById: "u-res-both",
    createdByName: "Mateo de León",
  },
  {
    id: "acc-5001",
    sipId: "5001@sip.flexivoice.net",
    displayName: "Tobias Lindqvist",
    email: "t.lindqvist@nordlogistik.fi",
    disabled: false,
    expiresAt: iso(311),
    createdAt: iso(-54),
    createdById: "u-admin",
    createdByName: "Nora Varga",
  },
  {
    id: "acc-5007",
    sipId: "5007@sip.flexivoice.net",
    displayName: "Aurora Night Desk",
    email: "night@nordlogistik.fi",
    disabled: false,
    expiresAt: iso(27),
    createdAt: iso(-119),
    createdById: "u-admin",
    createdByName: "Nora Varga",
  },
  {
    id: "acc-5019",
    sipId: "5019@sip.flexivoice.net",
    displayName: "Yusuf Demir",
    email: "y.demir@kalemtekstil.com.tr",
    disabled: false,
    expiresAt: iso(-3),
    createdAt: iso(-368),
    createdById: "u-admin",
    createdByName: "Nora Varga",
  },
  {
    id: "acc-6002",
    sipId: "6002@sip.flexivoice.net",
    displayName: "Sofia Braga",
    email: "sofia.braga@vitalcare.pt",
    disabled: false,
    expiresAt: iso(146),
    createdAt: iso(-31),
    createdById: "u-admin",
    createdByName: "Nora Varga",
  },
  {
    id: "acc-6014",
    sipId: "6014@sip.flexivoice.net",
    displayName: "VitalCare On-Call",
    email: "oncall@vitalcare.pt",
    disabled: true,
    expiresAt: iso(88),
    createdAt: iso(-160),
    createdById: "u-admin",
    createdByName: "Nora Varga",
    notes: "Paused during clinic renovation",
  },
  {
    id: "acc-6027",
    sipId: "6027@sip.flexivoice.net",
    displayName: "Hannah Whitfield",
    email: "h.whitfield@brightpath.co.uk",
    disabled: false,
    expiresAt: iso(12),
    createdAt: iso(-83),
    createdById: "u-res-both",
    createdByName: "Mateo de León",
  },
  {
    id: "acc-7003",
    sipId: "7003@sip.flexivoice.net",
    displayName: "Osaka Reception Trunk",
    email: "reception@kitamura-kk.jp",
    disabled: false,
    expiresAt: iso(402),
    createdAt: iso(-11),
    createdById: "u-admin",
    createdByName: "Nora Varga",
  },
];

export const MOCK_REQUESTS: AccessRequest[] = [
  {
    id: "req-8801",
    kind: "reseller",
    module: "sip",
    name: "Léa Berthier",
    email: "lea.berthier@ondaline.fr",
    phone: "+33 6 24 91 77 03",
    company: "Ondaline Communications",
    country: "France",
    website: "https://ondaline.fr",
    reason:
      "We resell hosted PBX to 60+ dental practices in Occitanie and want to provision SIP lines directly instead of emailing tickets.",
    submittedAt: iso(-1),
    status: "pending",
  },
  {
    id: "req-8802",
    kind: "account",
    module: "sip",
    name: "Ravi Anand",
    email: "ravi.anand@sattvalabs.in",
    phone: "+91 98453 20117",
    note: "Need a line for the Bengaluru lab intercom before the audit on the 14th.",
    submittedAt: iso(-2),
    status: "pending",
  },
  {
    id: "req-8803",
    kind: "account",
    module: "esim",
    name: "Marta Ilić",
    email: "m.ilic@adriaroam.hr",
    phone: "+385 91 448 2210",
    note: "Data-only eSIM for field surveyors along the Dalmatian coast.",
    submittedAt: iso(-3),
    status: "pending",
  },
  {
    id: "req-8804",
    kind: "reseller",
    module: "esim",
    name: "Kwame Boateng",
    email: "kwame@accralink.gh",
    phone: "+233 24 776 5510",
    company: "AccraLink Mobility",
    country: "Ghana",
    website: "https://accralink.gh",
    reason:
      "Distributing travel eSIMs across three retail branches; need self-service provisioning and monthly reconciliation.",
    note: "Existing SIP reseller of record since 2023.",
    submittedAt: iso(-4),
    status: "pending",
  },
  {
    id: "req-8805",
    kind: "account",
    module: "sip",
    name: "Elin Sørensen",
    email: "elin.sorensen@fjordtek.no",
    phone: "+47 458 22 190",
    note: "Replacement line — previous extension 5019 expired.",
    submittedAt: iso(-5),
    status: "pending",
  },
  {
    id: "req-8806",
    kind: "reseller",
    module: "sip",
    name: "Tomás Quiroga",
    email: "tquiroga@vozandina.cl",
    phone: "+56 9 6621 4408",
    company: "VozAndina SpA",
    country: "Chile",
    website: "https://vozandina.cl",
    reason:
      "Regional integrator for mining site comms; 200 seats forecast in year one.",
    submittedAt: iso(-7),
    status: "pending",
  },
  {
    id: "req-8807",
    kind: "account",
    module: "esim",
    name: "Noa Feldman",
    email: "noa.feldman@terrafleet.il",
    phone: "+972 52 331 8874",
    submittedAt: iso(-9),
    status: "approved",
  },
  {
    id: "req-8808",
    kind: "reseller",
    module: "sip",
    name: "Grigor Petrosyan",
    email: "g.petrosyan@mailhive.am",
    phone: "+374 55 12 44 09",
    company: "MailHive LLC",
    country: "Armenia",
    reason: "Bulk outbound campaigns.",
    submittedAt: iso(-11),
    status: "rejected",
    decisionReason:
      "Use case conflicts with acceptable-use policy on automated outbound dialing.",
  },
];
